version: '3.7' 
services: 
  influxdb: 
    image: influxdb:1.7.0
    container_name: influxdb 
    restart: always 
    ports: 
      - 8086:8086 
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
    volumes: 
      - /var/lib/influxdb:/var/lib/influxdb
    networks:
      - influxdbn

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    networks:
      - influxdbn


networks:
  influxdbn:
    driver: bridge
